# Demo 03 - Numpy and Pandas

In [1]:
import pandas as pd
import numpy as np
import time
import random

## List Compression

In [7]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

# Write a for loop for adding fruits that contain the letter 'a' to newlist 
for fruit in fruits:
    if 'a' in fruit:
        newlist.append(fruit)
    # if it starts with a
    #if fruit[0] == 'a': # we can also do fruit.startswith('a')
    #    newlist.append(fruit)
        
newlist

['apple', 'banana', 'mango']

In [6]:
'a' in 'apple'

True

In [5]:
'apple' in fruits

True

Template for list compression:

    [<do something> for item in <list> <condition>  ]

In [9]:
# Write a one liner

[fruit.capitalize() for fruit in fruits if 'a' in fruit]

['Apple', 'Banana', 'Mango']

More examples https://www.w3schools.com/python/python_lists_comprehension.asp

In [12]:
'apple banana cherry kiwi mango'.split()

['apple', 'banana', 'cherry', 'kiwi', 'mango']

In [13]:
"|||".join(["apple", "banana", "cherry", "kiwi", "mango"])

'apple|||banana|||cherry|||kiwi|||mango'

In [16]:
['apple', 4, 4.5, ['list1'], {}, set()]

['apple', 4, 4.5, ['list1'], {}, set()]

(slides)

## Array vs List

### Initalizing array

In [17]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [18]:
evenly_spaced_array = np.linspace(0, 9, 10)
evenly_spaced_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
np.linspace(1,100,50).shape

(50,)

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((5, 2)) # 5 by 2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.zeros((5, 2)).shape

(5, 2)

In [27]:
num_rows = np.zeros((5, 2)).shape[0]
num_rows

5

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((5, 5)) # 5 by 5 of all ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full(5, 'a') 

array(['a', 'a', 'a', 'a', 'a'], dtype='<U1')

**Question:** What is different about what is printed out compared to the previous arrays?

In [32]:
five_a_array = np.full(5, 'a')
five_a_array

array(['a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [33]:
five_a_array.dtype

dtype('<U1')

In [34]:
np.zeros(5).dtype

dtype('float64')

In [35]:
np.full((3, 3), 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.empty(10)

In [36]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(10, 20, step=2)

array([10, 12, 14, 16, 18])

In [38]:
np.arange(start=10, stop=20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(stop=20, start=10)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(20, 10)

array([], dtype=int64)

In [41]:
np.arange(20, 10, -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

(back to slides)

### Element-wise operations

In [43]:
numbers = [1,2,3,4,5]


[item + 5 for item in numbers]

[6, 7, 8, 9, 10]

In [46]:
np.arange(1,6) + 5

array([ 6,  7,  8,  9, 10])

In [60]:
random_array = np.random.rand(5)
random_array

array([0.22065749, 0.48998924, 0.34985879, 0.08573526, 0.54105478])

In [61]:
random_array * 5

array([1.10328747, 2.44994621, 1.74929394, 0.42867632, 2.70527389])

In [62]:
random_array / 5

array([0.0441315 , 0.09799785, 0.06997176, 0.01714705, 0.10821096])

In [63]:
random_array + 5

array([5.22065749, 5.48998924, 5.34985879, 5.08573526, 5.54105478])

In [64]:
random_array *= 5 # random_array = random_array * 5
random_array

array([1.10328747, 2.44994621, 1.74929394, 0.42867632, 2.70527389])

In [65]:
random_array > 1

array([ True,  True,  True, False,  True])

In [66]:
random_array == 1

array([False, False, False, False, False])

In [68]:
boolean_array = random_array > 1
type(boolean_array)

numpy.ndarray

In [70]:
boolean_array.dtype

dtype('bool')

#### Homogenous types

In [71]:
np.array([1,2,3]).dtype

dtype('int64')

In [76]:
np.array([1,2,3])[-1]

3

In [78]:
np.array([1,2,3])[1:]

array([2, 3])

In [79]:
np.array([1, "two", 3])

array(['1', 'two', '3'], dtype='<U21')

In [80]:
np.array([1, "two", 3]).dtype

dtype('<U21')

In [81]:
np.array([1, "two", 3])[0]

'1'

In [82]:
type(np.array([1, "two", 3])[0])

numpy.str_

In [85]:
type("this is an example string") == type(np.array([1, "two", 3])[0])

False

#### Adding Arrays vs Lists

In [87]:
list_one = [num for num in range(10)]
list_two = [num for num in range(10, 20)]

list_one, list_two, type(list_one)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 list)

In [88]:
list_one + list_two

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [89]:
added_list = []
for one, two in zip(list_one, list_two):
    added_list.append(one + two)
added_list

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

[do something for item in list <condition>]

In [90]:
[one + two  for one, two in zip(list_one, list_two)]

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [91]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

array1, array2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [92]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### Concatenating arrays

In [93]:
np.concatenate((array1, array2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Speed

In [98]:
list_one = [random.random() for i in range(int(1e7))] # create a list of 10k random numbers
list_two = [random.random() for i in range(int(1e7))]

array_one = np.array(list_one)
array_two = np.array(list_two)

In [99]:
list_three = []
start = time.time()
for one, two in zip(list_one, list_two):
    list_three.append(one * two)
end = time.time()
end - start

3.387997627258301

In [100]:
start = time.time()
array_three = array_one * array_two
end = time.time()
end - start

0.04576921463012695

Let's increase the size of the list to 1e8 and see if there is a larger difference

In [ ]:
np.array([1,2,3,4])

In [ ]:
np.arange(20)

In [ ]:
type(np.arange(20))

## Numpy Math Functions

In [101]:
random_array = np.random.randn(30)
random_array

array([-0.26102565,  1.19786751, -0.04273852,  1.19557279, -0.38429647,
       -0.08511161,  0.02987767, -1.71108574,  1.58880855, -0.37785036,
        0.75643005,  0.13669353, -0.67790953,  0.77678411,  0.43531734,
       -0.02492461,  0.27366968,  0.64593856, -0.00222571,  1.31239193,
       -0.16477506, -1.98562236,  0.81843284, -1.84680836,  0.08840747,
        1.75900984, -0.36088447,  1.00172109,  0.58522671, -0.26250973])

In [102]:
random_array.mean()

0.14714604991347643

In [106]:
example_array_one = np.arange(10) * 100
example_array_one.max()

900

In [107]:
example_array_one.argmax()

9

In [108]:
example_array_one

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [103]:
random_int_array = np.random.randint(low = 0, high = 10, size = 50)
random_int_array

array([0, 2, 9, 4, 8, 8, 1, 4, 1, 2, 7, 8, 6, 5, 3, 6, 9, 0, 1, 0, 3, 5,
       2, 3, 6, 0, 0, 1, 0, 4, 9, 8, 0, 0, 6, 7, 7, 9, 1, 4, 5, 9, 9, 8,
       4, 8, 1, 4, 1, 6])

**Question** Find the median of `random_int_array`

In [110]:
np.median(random_int_array)

4.0

(back to slides)
## Series

In [112]:
arr

array([5, 4, 2, 0, 1])

In [121]:
arr = np.array([5, 4, 2, 0, 1])
s1 = pd.Series(arr)
s1

0    5
1    4
2    2
3    0
4    1
dtype: int64

**Question:** What are the indices in `s1`?

In [115]:
s1.max()

5

In [116]:
s1.argmax()

0

In [118]:
s1.index + 1

RangeIndex(start=1, stop=6, step=1)

In [122]:
s1.index += 1
s1

1    5
2    4
3    2
4    0
5    1
dtype: int64

In [123]:
s2 = pd.Series(arr, index=['a','b','c','d','e'])
print(s2)

a    5
b    4
c    2
d    0
e    1
dtype: int64


**Question:** What are the indices in `s2`?

In [125]:
arr[2]

2

In [127]:
s2['a']

5

In [128]:
s2[0]

5

In [129]:
mydict = {'a': 1, 'b': 2, 'c': 3}
s3 = pd.Series(mydict)
s3

a    1
b    2
c    3
dtype: int64

In [130]:
mydict

{'a': 1, 'b': 2, 'c': 3}

In [131]:
s4 = pd.Series(mydict, index=['b','a','d'])
s4

b    2.0
a    1.0
d    NaN
dtype: float64

**Question:** What is `Nan`?

In [138]:
type(np.nan), type(s4[0])

(float, numpy.float64)

**Question:** Why is the Series now a series of floats rather than ints?

In [ ]:
s4.isna()

In [140]:
s5 = pd.Series(5, index=['a','b','c'])
s5

a    5
b    5
c    5
dtype: int64

In [141]:
pd.Series("string", index=np.arange(5))

0    string
1    string
2    string
3    string
4    string
dtype: object

### Indexing Series

In [ ]:
s5[1]

In [ ]:
s5['b']

### Vectorized operations

In [142]:
s5, s3

(a    5
 b    5
 c    5
 dtype: int64,
 a    1
 b    2
 c    3
 dtype: int64)

In [143]:
s5 + s3

a    6
b    7
c    8
dtype: int64

#### Adding mismatched indices

In [144]:
s1, s3

(1    5
 2    4
 3    2
 4    0
 5    1
 dtype: int64,
 a    1
 b    2
 c    3
 dtype: int64)

In [145]:
s1 + s3

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
dtype: float64

In [146]:
5 + np.nan

nan

In [147]:
s3

a    1
b    2
c    3
dtype: int64

In [148]:
s3.mean()

2.0

#### Additional functions

In [149]:
np.exp(s1)

1    148.413159
2     54.598150
3      7.389056
4      1.000000
5      2.718282
dtype: float64

In [ ]:
s2

In [151]:
np.log(s2), s2

(a    1.609438
 b    1.386294
 c    0.693147
 d        -inf
 e    0.000000
 dtype: float64,
 a    5
 b    4
 c    2
 d    0
 e    1
 dtype: int64)

In [152]:
s2.describe()

count    5.000000
mean     2.400000
std      2.073644
min      0.000000
25%      1.000000
50%      2.000000
75%      4.000000
max      5.000000
dtype: float64

(back to slides)

## DataFrames



### Constructing a DataFrame

##### Empty dataframe

In [153]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

##### Based on Dictionary

In [154]:
s2, s3

(a    5
 b    4
 c    2
 d    0
 e    1
 dtype: int64,
 a    1
 b    2
 c    3
 dtype: int64)

In [155]:
mydict = {'column1': s2, 'column2': s3}
df1 = pd.DataFrame(mydict)

df1

column1  column2
a        5      1.0
b        4      2.0
c        2      3.0
d        0      NaN
e        1      NaN

Let's look at the indices of `df1`.

In [156]:
df1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

**Question: Why are these the indices?**
    
<details>
<summary>Hint</summary>
<b>Let's look at `s2` and `s1`</b>  
</details>

In [157]:
df1.dtypes

column1      int64
column2    float64
dtype: object

**Question:** What if the indices don't match up?

In [158]:
s1, s2

(1    5
 2    4
 3    2
 4    0
 5    1
 dtype: int64,
 a    5
 b    4
 c    2
 d    0
 e    1
 dtype: int64)

In [159]:
mydict = {'column1': s1, 'column2': s2}
df2 = pd.DataFrame(mydict)

df2

column1  column2
1      5.0      NaN
2      4.0      NaN
3      2.0      NaN
4      0.0      NaN
5      1.0      NaN
a      NaN      5.0
b      NaN      4.0
c      NaN      2.0
d      NaN      0.0
e      NaN      1.0

In [160]:
df2.index

Index([1, 2, 3, 4, 5, 'a', 'b', 'c', 'd', 'e'], dtype='object')

In [162]:
s1.index

RangeIndex(start=1, stop=6, step=1)

#### Adding Columns to a dataframe

2 ways:
- `df.assign(<column name>=<list>)`
- `df[<column name>] = <list>`  - access like a collection

In [163]:
df3 = pd.DataFrame()
df3

Empty DataFrame
Columns: []
Index: []

In [165]:
df3.assign(column_one = np.random.randn(5))

column_one
0   -0.051360
1   -1.021937
2    1.068062
3   -1.250372
4   -0.749344

In [167]:
df3 = df3.assign(column_one = np.random.randn(5))
df3

column_one
0    0.280962
1    0.056487
2    1.676626
3   -1.245970
4   -1.273119

In [169]:
df3['column_two'] = 5
df3

column_one  column_two
0    0.280962           5
1    0.056487           5
2    1.676626           5
3   -1.245970           5
4   -1.273119           5

In [170]:
df3.size

10

In [171]:
df3.shape

(5, 2)

Adding a new column of a different length

**Question:** Why do we think the next line will throw an error?

In [172]:
np.random.randn(6)

array([ 1.01153164,  0.7415595 ,  1.38637033, -0.58985323,  1.22718878,
        0.46597923])

In [173]:
df3['three'] = np.random.randn(6)

ValueError: Length of values (6) does not match length of index (5)

In [ ]:
df3['example'] = 'example'
df3

### Pudding Film Dialogue Data

The data we will work with today comes from https://pudding.cool/2017/03/film-dialogue/

> Lately, Hollywood has been taking so much shit for rampant sexism and racism. The prevailing theme: white men dominate movie roles.

> But it’s all rhetoric and no data, which gets us nowhere in terms of having an informed discussion. How many movies are actually about men? What changes by genre, era, or box-office revenue? What circumstances generate more diversity?

> We didn’t set out trying to prove anything, but rather compile real data. We framed it as a census rather than a study. So we Googled our way to 8,000 screenplays and matched each character’s lines to an actor. From there, we compiled the number of words spoken by male and female characters across roughly 2,000 films, arguably the largest undertaking of script analysis, ever.

In [174]:
!wc -l data/Pudding-Film-Dialogue-Clean.csv

23048 data/Pudding-Film-Dialogue-Clean.csv


In [175]:
!head data/Pudding-Film-Dialogue-Clean.csv

"title","release_year","character","gender","words","proportion_of_dialogue","age","gross","script_id"
"The Bridges of Madison County",1995,"Betty","woman",311,0.0486393494,35,142,280
"The Bridges of Madison County",1995,"Carolyn Johnson","woman",873,0.1365342509,,142,280
"The Bridges of Madison County",1995,"Eleanor","woman",138,0.0215827338,,142,280
"The Bridges of Madison County",1995,"Francesca Johns","woman",2251,0.3520487957,46,142,280
"The Bridges of Madison County",1995,"Madge","woman",190,0.0297153581,46,142,280
"The Bridges of Madison County",1995,"Michael Johnson","man",723,0.1130747576,38,142,280
"The Bridges of Madison County",1995,"Robert Kincaid","man",1908,0.2984047545,65,142,280
"15 Minutes",2001,"Bobby Korfin","man",328,0.0360122969,,37,623
"15 Minutes",2001,"Daphne Handlova","woman",409,0.0449055775,28,37,623


In [176]:
pd.read_csv("data/Pudding-Film-Dialogue-Clean.csv")

title  release_year        character gender  \
0      The Bridges of Madison County          1995            Betty  woman   
1      The Bridges of Madison County          1995  Carolyn Johnson  woman   
2      The Bridges of Madison County          1995          Eleanor  woman   
3      The Bridges of Madison County          1995  Francesca Johns  woman   
4      The Bridges of Madison County          1995            Madge  woman   
...                              ...           ...              ...    ...   
23042           Beauty and the Beast          1991          Lumiere    man   
23043           Beauty and the Beast          1991          Maurice    man   
23044           Beauty and the Beast          1991  Monsieur D'Arqu    man   
23045           Beauty and the Beast          1991       Mrs. Potts  woman   
23046           Beauty and the Beast          1991         Wardrobe  woman   

       words  proportion_of_dialogue   age  gross  script_id  
0        311                0.048639  35.0  142.0        280  
1        873                0.136534   NaN  142.0        280  
2        138                0.021583   NaN  142.0        280  
3       2251                0.352049  46.0  142.0        280  
4        190                0.029715  46.0  142.0        280  
...      ...                     ...   ...    ...        ...  
23042   1063                0.104636  56.0  452.0       9254  
23043   1107                0.108967  71.0  452.0       9254  
23044    114                0.011222  58.0  452.0       9254  
23045    564                0.055517  66.0  452.0       9254  
23046    121                0.011911  54.0  452.0       9254  

[23047 rows x 9 columns]

In [177]:
df = pd.read_csv("data/Pudding-Film-Dialogue-Clean.csv")
df.head(5)

title  release_year        character gender  words  \
0  The Bridges of Madison County          1995            Betty  woman    311   
1  The Bridges of Madison County          1995  Carolyn Johnson  woman    873   
2  The Bridges of Madison County          1995          Eleanor  woman    138   
3  The Bridges of Madison County          1995  Francesca Johns  woman   2251   
4  The Bridges of Madison County          1995            Madge  woman    190   

   proportion_of_dialogue   age  gross  script_id  
0                0.048639  35.0  142.0        280  
1                0.136534   NaN  142.0        280  
2                0.021583   NaN  142.0        280  
3                0.352049  46.0  142.0        280  
4                0.029715  46.0  142.0        280

In [178]:
df.keys()

Index(['title', 'release_year', 'character', 'gender', 'words',
       'proportion_of_dialogue', 'age', 'gross', 'script_id'],
      dtype='object')

In [179]:
df.columns

Index(['title', 'release_year', 'character', 'gender', 'words',
       'proportion_of_dialogue', 'age', 'gross', 'script_id'],
      dtype='object')

In [180]:
df.columns == df.keys()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [181]:
np.all(df.columns == df.keys())

True

**Question:** Let's randomly sample 10 rows from the dataframe?

In [183]:
# How can we find out how to do that?
df.sample(10)


title  release_year        character gender  words  \
20525  Final Destination 3          2006           Hector    man    665   
2455              Predator          1987          Ramirez    man    258   
21703       Old Boyfriends          1979     Dylan Turrin  woman    290   
3734        A Few Good Men          1992  Lt. Dave Spradl    man    306   
12244          El cantante          2006            Puchi  woman   2917   
12688           Evil Angel          2009            Shawn    man    472   
1189     Final Destination          2000    Carter Horton    man    400   
2713              Rushmore          1998    Magnus Buchan    man    169   
5547            Collateral          2004        Peter Lim    man    114   
11267             Twilight          2008             Eric    man    308   

       proportion_of_dialogue   age  gross  script_id  
20525                0.081535   NaN   71.0       7904  
2455                 0.085800   NaN  132.0       1244  
21703                0.041036  15.0    NaN       8450  
3734                 0.007228  36.0  295.0       1538  
12244                0.411599  37.0   10.0       3986  
12688                0.061426   NaN    NaN       4178  
1189                 0.138937  28.0   86.0        915  
2713                 0.031279   NaN   31.0       1291  
5547                 0.010014   NaN  140.0       2035  
11267                0.021502  27.0  231.0       3621

**Question:** How many rows and columns do we have?

**Question:** What are the different types in each column?

In [184]:
df.dtypes

title                      object
release_year                int64
character                  object
gender                     object
words                       int64
proportion_of_dialogue    float64
age                       float64
gross                     float64
script_id                   int64
dtype: object

### Listing columns

**Question:** On your own using the documentation, find the two ways we can list the columns.

*Hint* One way is a dataframe function and the other is an attribute/instance


### Accessing columns

3 options:

- `df.get(<column name>)`
- `df[<column name>]` - access like a collection
- `df.<column name>` - access like a attribute/method 

In [186]:
# try first option here
df.get('gender')

0        woman
1        woman
2        woman
3        woman
4        woman
         ...  
23042      man
23043      man
23044      man
23045    woman
23046    woman
Name: gender, Length: 23047, dtype: object

In [185]:
# try second option here
df['gender']

0        woman
1        woman
2        woman
3        woman
4        woman
         ...  
23042      man
23043      man
23044      man
23045    woman
23046    woman
Name: gender, Length: 23047, dtype: object

In [187]:
# try third option here
df.gender

0        woman
1        woman
2        woman
3        woman
4        woman
         ...  
23042      man
23043      man
23044      man
23045    woman
23046    woman
Name: gender, Length: 23047, dtype: object

### Accessing rows

In [192]:
## Access by index label

df.loc[4]

title                     The Bridges of Madison County
release_year                                       1995
character                                         Madge
gender                                            woman
words                                               190
proportion_of_dialogue                         0.029715
age                                                46.0
gross                                             142.0
script_id                                           280
Name: 4, dtype: object

In [190]:
## Access by location

df.iloc[-1]

title                     Beauty and the Beast
release_year                              1991
character                             Wardrobe
gender                                   woman
words                                      121
proportion_of_dialogue                0.011911
age                                       54.0
gross                                    452.0
script_id                                 9254
Name: 23046, dtype: object

### Sorting dataframe

In [ ]:
df.keys()

**Question:** What column should we sort by?

**Question:** What two columns should we sort by?

Return type of dataframe functions

### Querying 

In [ ]:
df['age'] > 10

In [ ]:
old_movies = df[df['age'] > 10]
old_movies

Let's look at the indices

**Question:** What do we notice about these indices?

Let's reset the indices

In [ ]:
old_movies.reset_index()

Let's not include the original index

In [ ]:
df.reset_index?

#### Querying on Multiple Conditions

In [ ]:
df[
    (df['release_year'] < 1930)
    &
    (df['gender'] == 'man')
]

In [ ]:
df

### Values in a column

**Question:** Based on everything we've seen so far, how can we determine the set of values that are in a column?

<details>
<summary>Hint</summary>
<b>1. Accessing the column; 2. convert the column (Series) to a set</b>  
</details>

In [ ]:
#skip

In [ ]:
#skip

`unique()`

In [ ]:
df['gender'].unique()

**Question:** How many rows have their gender assigned as `woman`, `man`, or `?`

In [ ]:
df['gender'].value_counts()


### Grouping 

Let's group by gender

In [ ]:
gender_groups = df.groupby('gender')
gender_groups

In [ ]:
Now let's find the mean/average values of the other columns for each gender

In [ ]:
gender_groups.mean()

**What just happened?**

1. The table’s rows are split into groups according to cause. 
    - All of the rows whose gender is 'man' are placed into one group,
    - All of the rows whose gender is 'woman' are placed into another group.
    - All of the rows whose gender is `?` are placed into another group

2. Each group is aggregated into a single row by average the value of entries in each of the group’s columns.

3. The resulting rows are combined to form a new table, with one row for every group.

**Other aggregation methods:**
- .median()
- .max()
- .min()
- .count()

In [ ]:
df.groupby('gender').count()

### Function on a cell

> Defining our own functions allows us to make tables even more powerful. One way to use tables with functions is to pass the table into the function as one of its inputs, as we saw in the example above. In some situations, however, we don’t want to apply the function to the entire table, but rather to each entry in one of the table’s columns. In these cases, we can use the .apply method.
(https://eldridgejm.github.io/dive_into_data_science/02-data_sets/apply.html#the-apply-series-method)

Let's write a function to get the word in a movie title

In [ ]:
def get_first_word_in_title(title):
    return title.split()[0]

Now let's apply the function to the title column

In [ ]:
df['title'].apply(get_first_word_in_title)

#### .map()